### ISSUE TITLE
Magic number mismatch

### ISSUE THREAD

**Issue by makc** [xBimTeam/XbimWebUI#184] opened 2018-05-22 18:15 UTC
I have these files from someone who claims they are both same format and, at a glance, the inside looks similar, however the magic numbers do not match. Do you maybe know what this other file is, or how to convert it so that the magic number does match?

![screen shot 2018-05-22 at 21 15 14](https://user-images.githubusercontent.com/242577/40381774-4ca5f156-5e05-11e8-90d5-88eccc22df7d.png)

**Comment by martin1cerny** [comment] 2018-05-23 06:29
You are better to ask the person who provided you with the data. I don't think these two files look similar. The second file seems to contain some semantic data (`Brick, Common` string at the end of your snippet). WexBIM file doesn't contain any strings. It only contains numbers representing geometric data, indices and control sums.

So, I can definitely confirm that second file is not wexBIM stream but you will need to investigate it yourself to find what it is. Once you know what it is you can try to convert the content into wexBIM as long as it contains geometry data.

**Comment by martin1cerny** [comment] 2018-06-07 08:20
Can I close this? It is not a bug in any of our code. You just need to find what you have been given as a source data.

**Closed** 2018-06-07 13:43 UTC
Labels: invalid
