### ISSUE TITLE
Error while rendering model in Firefox and Chrome [CORS policy error].

### ISSUE THREAD

**Issue by Dhruti03** [xBimTeam/XbimWebUI#170] opened 2018-03-05 09:00 UTC
Hello,
While rendering 3D model, the model is getting rendered in 'Microsoft Edge' browser but shows below mentioned error in Mozilla, Chrome and Internet Explorer.

> Failed to fetch semantic JSON data from server. Server code:404. This might be due to CORS policy of your browser if you run this as a local file.

 Kindly help me to know what changes would be required to get it rendered in all browsers or is there any manual/ help file for reference. Please find attached file.
[3DModelTest.zip](https://github.com/xBimTeam/XbimWebUI/files/1780103/3DModelTest.zip)
[3DModelTest(wexbim).zip](https://github.com/xBimTeam/XbimWebUI/files/1780127/3DModelTest.wexbim.zip)

Thanks.

**Comment by martin1cerny** [comment] 2018-03-05 09:43
Do you serve your page from the web server?

**Comment by martin1cerny** [comment] 2018-03-05 11:19
Closing as a duplicate of #171.

**Closed by martin1cerny** 2018-03-05 11:19 UTC
