### ISSUE TITLE
Showing the whole model

### ISSUE THREAD

**Issue by palktonderAtpowelno** [xBimTeam/XbimWebUI#150] opened 2017-10-27 16:53 UTC
Hi,

We are using the viewer to show a 3D model in our web page, but we are struggling because only parts of the model is visible. It seems like the "world" is too small so that parts of the model is not presented. Is there a way to make sure the whole model is visible?

**Comment by CBenghi** [comment] 2017-10-27 20:52
Hello,
it's difficult to assess your problem without a file.
Can you check that the model is displayed correctly in XbimXplorer before we do anything else?
http://docs.xbim.net/downloads/xbimxplorer.html
Thanks,
Claudio

**Comment by palktonderAtpowelno** [comment] 2017-10-28 11:51
Actually, as you can see from the image below the file works fine in the viewer:
![image](https://user-images.githubusercontent.com/1410875/32133916-b1c4c0a6-bbe1-11e7-869b-5f1af63d1fc6.png)

The problem is not that the file doesn't show in the xViewer, it's rather that some parts of it aren't displayed. It's like there's a clipping plane in action, but we have not defined any. As we zoom out, more and more of the model disappears until it's totally gone.
![image](https://user-images.githubusercontent.com/1410875/32133853-653422fa-bbe0-11e7-98f3-d5de0c18c16b.png)
It's as if the visible world is defined too narrow for our model (is that what the _mvMatrix is for?). Does this make any sense? Please help me, because I don't know where to start to make sure the whole model is visible to the user

**Comment by CBenghi** [comment] 2017-10-28 15:20
This tells me that the geometry and the regions are calculated correctly by the engine.
The problem must be with the frustum in the opengl-es viewer.
That is @martin1cerny 's domain, but if he does not step in I'll be happy to have a look and try to help.
Claudio

**Comment by martin1cerny** [comment] 2017-10-30 07:51
What you see in the viewer is perspective camera's far clipping plane being too close for the size of the model. This usually happens when you zoom too far from the model. The default setting makes this 50 times bigger than maximum size of the region so it usually works fine. It can only go wrong if xBIM algorithm thinks there are more distinct regions. The viewer will than only use the most populated one (where population is number of geometrical objects in it). If this region is relatively small it won't work for a bigger scene like yours. 

One think you can try to see if it is really far clipping plane problem is to set

```js
viewer.perspectiveCamera.far *= 2;
```

**Comment by palktonderAtpowelno** [comment] 2017-10-30 14:01
Using
`viewer.perspectiveCamera.far *= 5;`
I'm able to zoom out and see the whole model without anything disappearing. But that was from trial and error so I'm wondering how this can be handled generically, given that I load different models. 

BTW: how can I set the zoom so that the whole model is visible from the start? Now it zooms in tight on the same, but random object

**Comment by martin1cerny** [comment] 2017-10-30 14:20
If you call zoom function without any arguments it will use the region to zoom to full extent. If the region is wrong than zoom will do the same. The problem is in the code in Xbim.Essentials which creates WexBIM file. That is computing the regions. The algorithm was used extensively on building models but your model seems to contain many discrete objects so it might evaluate it as many regions. The viewer doesn't have very good support for this multi-region scenario.

**Comment by martin1cerny** [comment] 2017-10-30 14:22
Sorry, I was wrong in saying that this happens in Xbim.Essentials. I just checked and it is deep down in Xbim.Geometry when geometry is being processed.

**Comment by palktonderAtpowelno** [comment] 2017-10-30 14:27
Yes, our models are infrastructure project with roads, tunnels etc. so there might be multiple items stretched over long distances.

**Comment by martin1cerny** [comment] 2017-10-30 15:29
WexBIM file contains information about all of them but the viewer currently only uses the most populated one. Feel free to make a pull request with some code to handle these situations. The reason we made it like this is that if there are objects spread over large area they are often not visible at all because that is more GIS-like visualization and should use symbols rather than real geometry. When looking closer I can imagine some functionality which would either present all regions in their own viewports or iterating over regions. But all of these would still need some kind of general overview for first level navigation. But first step is to merge these regions and see if it is good enough for your scenarios.

**Comment by CBenghi** [comment] 2017-10-30 15:31
@palktonderAtpowelno,
In WindowsUI we recalc the far-plane as the camera moves around depending on the selected region.
If you want inspiration, have a look at the code in the develop branch though... I'm not sure the best code is already merged in master.
Best,
Claudio

**Comment by martin1cerny** [comment] 2021-08-03 08:39
We have published new and much improved version of the viewer as an [npm package](https://www.npmjs.com/package/@xbim/viewer). It calculated the far clipping plane based on the size of the region and camera position.

**Closed by martin1cerny** 2021-08-03 08:39 UTC
Labels: enhancement
