### ISSUE TITLE
Can't convert to wexBIM

### ISSUE THREAD

**Issue by OmarKhairyHosny** [xBimTeam/XbimWebUI#276] opened 2020-02-06 09:05 UTC
I am trying to do wexbim example "https://docs.xbim.net/examples/creating-wexbim-file.html"
by creating console app and install the latest version of libraries from nuget

after running show the error below
![73344081-61166880-428a-11ea-83a1-973024ab4822](https://user-images.githubusercontent.com/41702983/73921692-7e71b500-48d0-11ea-929c-bfafb0d27432.png)

Update : this problem has happen when I am trying to generate wexbim file with version 5 and work fine with 4

**Comment by andyward** [comment] 2020-02-06 09:12
Duplicate of #274

**Closed by andyward** 2020-02-06 09:12 UTC
