### ISSUE TITLE
Merging two ifc files

### ISSUE THREAD

**Issue by Anu004** [xBimTeam/XbimWebUI#166] opened 2018-02-14 10:07 UTC
Hi,

Is it possible to do merging of 2 ifc models using the xbim libraries?

**Comment by martin1cerny** [comment] 2018-02-14 11:31
Just load as many wexBIM files as you want.

**Comment by theextremeandy** [comment] 2018-02-22 20:03
Hi Martin,
it is true, that you can load an indefinite number of models using the load method
I also passed the property tag to recognize its succession
but after loading two models the elements of one of the two are not selectable
can you suggest me the solution?

**Comment by martin1cerny** [comment] 2018-02-23 08:24
You are right, 'pick' event only gets product ID but doesn't identify the model it comes from. It was meant to support scenario where all models loaded are essentially parts of a single original model. Element identification works now in a way where the product ID is encoded as RGB colour, rendered to in-memory framebuffer and decoded from the image. Your scenario would require to do the same again for the product model. This is possible but not implemented at the moment.

**Comment by theextremeandy** [comment] 2018-02-23 09:26
Thanks Martin
now I must quickly find a solution
and I return to inform you as soon as possible.

**Comment by theextremeandy** [comment] 2018-06-05 12:36
Hi @martin1cerny 
can you please explain this better?

> Element identification works now in a way where the product ID is encoded as RGB colour, rendered to in-memory framebuffer and decoded from the image. Your scenario would require to do the same again for the product model.

**Comment by martin1cerny** [comment] 2018-06-05 13:17
Please, see the code used to get ID for technical details of the solution.

**Comment by LloydPickering** [comment] 2018-06-05 14:06
@theextremeandy the method used is broadly similar to the following article: http://xeolabs.com/articles/scenejs-ray-picking-technique

Right now the ProductID is encoded as RGB. You would need to change it to add in a further abstraction. 

If you have Model A with 100 products and model B with 50 products, then instead of encoding 100 values in the buffer, you need to encode 150 values, and remember that the 1st 100 [0-99] are for Model A and the next 50 [100-149] for Model B. That way if the id that comes back is [74], you know it is the 75th product in Model A. If [124] comes back, you know it is the 25th Product in Model B.

**Comment by theextremeandy** [comment] 2018-06-05 18:20
hi @LloydPickering 
thank you for your suggestion
but I'am confused
as I said:
>  it is true, that you can load an indefinite number of models using the load method
I also passed the property tag to recognize its succession
but after loading two models the elements of one of the two are not selectable

the problem is that function xViewer#getState 
`
viewer.on("pick", function (args) {
if (args.id == null) {
var id = args.id;
viewer.getState([id])
`
returns a null value for all entities of the second model, 
so no entity is selectable!

**Comment by theextremeandy** [comment] 2018-06-07 05:45
hi,
I modified the getState function code in the xbim-viewer.js file
from:
xViewer.prototype.getState = function (id) {
     var state = null;
     this._handles.forEach (function (handle) {
         state = handle.getState (id);
         if (state! == null) {
             return;
         }
     }, this);
     return state;
};

to:
xViewer.prototype.getState = function (id) {
     var state = null;
     var varstate = '';
     this._handles.forEach (function (handle) {
         state = handle.getState (id);
         if (state! == null) {
             varstate = state;
             return;
         }
     }, this);
     return varstate;
};

I hope it is also useful to others
andrea

**Comment by martin1cerny** [comment] 2018-06-07 08:17
The only difference is that original implementation will return first state and your implementation will return last state found. But I can't see how it helps with the issue.

**Comment by theextremeandy** [comment] 2018-06-07 08:33
I think that the original reset the value of state if the last was null
this implementation will return the state found in all handles

**Comment by martin1cerny** [comment] 2018-06-07 08:45
Sorry, you are right, there is a bug which will make the result always null. It is obviously not widely used function :-) But your implementation will not aggregate the result as you expect.

**Comment by theextremeandy** [comment] 2018-06-07 09:14
do you suspect a duplication of id in the different models?

**Comment by martin1cerny** [comment] 2018-06-07 09:21
Yes, there *will* be a duplicity of IDs across multiple models.

**Comment by theextremeandy** [comment] 2018-06-07 09:50
yes, it's true, so now it would be necessary to follow @LloydPickering and rename all id with id value plus id model
any suggestions?

**Comment by martin1cerny** [comment] 2018-06-07 10:06
As I said before:
> Please, see the code used to get ID for technical details of the solution.

**Comment by theextremeandy** [comment] 2018-06-08 10:11
I searched and searched hard in the _getID function
but I do not see where I can find the solution

the _getID function calculates id based on the expression
var id = result [0] + result [1] * 256 + result [2] * 256 * 256;
and result buffer comes from the readPixels function

nothing that allows us to know what the model of the selected element is

**Comment by LloydPickering** [comment] 2018-06-08 11:10
...that's why you need to alter it. 

Right now it expects a single model and writes the product ids for that model to the buffer. A new updated version of the code needs to be modified so that it instead writes a dictionary lookup containing a separate and unique id for every product in the superset of models. When this is read, you use the dictionary to find out which model/product it is referring to.

Consider you have 2 models [A,B], each with a single product [ids of 56 and 92 respectively].

Currently the buffer is written with [56] which matches the product in A. There is no way to know reference any item in B. It will return Null if Product 92 is selected.

We need to create a dictionary similar to the below:
1: [A,56]
2: [B,92]

We need to populate the buffer with the IDs of the dictionary [1 & 2] rather than the Product IDs from the models.

When we get the new ID back, it will be 1 or 2 and we can then use the dictionary to find which Model and Product ID it refers to.

I'll say this again. This code does not currently exist. It needs to be written. There are two locations where this logic needs to be applied. 1) Where the buffer is written [we need to write the relevant dictionary id of the product in the dictionary] 2) Where the buffer is read [the number returned from readPixels needs to be the id of the dictionary]

**Comment by theextremeandy** [comment] 2018-06-08 15:23
hi @LloydPickering
thank you for your answer
working on buffer is not so simple :-(
are you referring to this part of the data?

![screen shot 06-08-18 at 05 20 pm](https://user-images.githubusercontent.com/18160434/41166364-5d66b87a-6b40-11e8-9072-307adb3f28b2.PNG)

**Comment by LloydPickering** [comment] 2018-06-08 15:40
Yes and no. That's not the buffer. The buffer is part of the graphics system, webgl. However the screenshot you have posted contains the productID fields you will need to use to create the dictionary (for reference in my example the productID were the values 56 & 92).

**Comment by theextremeandy** [comment] 2018-06-08 16:34
@LloydPickering 
excuse me (worse than a leech :-( )
is the second one Uint8 array to which you refer?

![screen shot 06-08-18 at 06 27 pm](https://user-images.githubusercontent.com/18160434/41169701-1009cf18-6b4a-11e8-9517-c8ebc7fc2d32.PNG)

**Comment by LloydPickering** [comment] 2018-06-11 08:42
@theextremeandy I'm not 100% sure as I didn't work on this specific code base (we wrote a web viewer which predated this one using the same technique).

I think (but i'm not certain) you are looking for xbim-model-geometry.debug.js ln121 onwards. productLabel would change to the dictionary lookup id.
`var map = {
            productID: productLabel,
            type: prodType,
            bBox: bBox,
            spans: []
        };`

This is as far as I can take it as I don't know the codebase here well myself, I just know the theory behind what needs to be done, and I don't have time to do it myself.

**Comment by theextremeandy** [comment] 2018-06-11 17:18
Thank you @LloydPickering 
I will have a look at this code and come back to inform you  
if I discover something interesting
;-)

**Comment by proiettimar74** [comment] 2020-05-21 16:28
Hi @LloydPickering and  @theextremeandy,
do you have news about this issue?
I have the same problem to find the right element only with id (productID), becouse I can't add any other usefull information to the "pick" event of mouse in the canvas . 
I load more xBim file in the canvas and  I found out that you can have the same productID on different files. If I pick an element in the canvas, I only get the id, but I need to get xBim file information to pass the value to the xBrowser.prototype.activateEntity function 
xBrowser.prototype.activateEntity = function (id, event) {....}

the method  _getID (id = viewer._getID(viewX, viewY)) should also value the relationship model,  so that I could use it in:

xBrowser.prototype.activateEntity = function (id, MODELKEY, event) {   
    if (!this._model) return;
    var entity = this._model[MODELKEY].getEntity(id);
    if (entity)  this._fire('entityActive', { entity: entity, event: event });          
    }

any suggestions?

**Comment by theextremeandy** [comment] 2020-05-22 14:01
Hi @proiettimar74 
I'm terribly busy right now
I would like to go back to the code to find the explanation for the problem
however the externalID is generated, as correctly explained by @martin1cerny   and @LloydPickering, by a calculation of the colors of the selected pixel.
this is the reason for the duplication.
and in that selection you have no way to intercept which model it is.
this is the reason for the difficulty of the solution

**Comment by LloydPickering** [comment] 2020-05-22 14:55
I am not involved much with Xbim anymore due to a change in jobs a couple of years ago, but in terms of a hint, you would need to reindex all the product ids of the individual models into a lookup table so there are no clashes, and instead alter the picking code to use this new index for pick targeting.

ie:

id1 = Model 1, Product 1
id2 = Model 1, Product 5
id3 = Model 2, Product 1

**Comment by martin1cerny** [comment] 2020-05-22 15:39
If you use `develop` version you will get both `elementId` and `modelId` from [pick event](https://github.com/xBimTeam/XbimWebUI/blob/develop/Xbim.WeXplorer/Viewer/viewer.ts#L1078). `ModelId` is the number you get from [loaded event](https://github.com/xBimTeam/XbimWebUI/blob/develop/Xbim.WeXplorer/Viewer/viewer.ts#L897). No need to renumber the model or anything.

**Comment by theextremeandy** [comment] 2020-05-22 15:44
hi @martin1cerny 
very good news!
thanks!

**Comment by martin1cerny** [comment] 2020-05-22 15:56
I think I can close this now.

**Closed by martin1cerny** 2020-05-22 15:56 UTC
Labels: enhancement, question

**Comment by proiettimar74** [comment] 2020-05-25 17:55
Thanks for the answer.

I have anywhere a problem to obtain the right modelId.

The getID function return the right id, but return a strange value of modelid.
modelid is sometimes a great number is (1192802, 9980292 for example), or has the same value of id variable.
Instead I expect value like 0, 1, 2, 3,..., which are the  number of federated file load


xViewer.prototype.getID = function (x, y, modelId) {
   ....
   ....
this._handles.forEach(function (handle) {
        if (!handle.stopped) {
            if (modelId) {
                gl.uniform1i(this._colorCodingUniformPointer, handle.id);
            }
            handle.setActive(this._pointers);
            handle.draw();
        }
    }, this);

    //call all after-drawId plugins
    this._plugins.forEach(function (plugin) {
        if (!plugin.onAfterDrawId) {
            return;
        }
        plugin.onAfterDrawId();
    }, this);

    //get colour in of the pixel
    var result = new Uint8Array(4);
    gl.readPixels(x, y, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, result);
    this.X = x;
    this.Y = y;

    //reset framebuffer to render into canvas again
    gl.bindFramebuffer(gl.FRAMEBUFFER, null);

    //free GPU memory
    gl.deleteTexture(texture);
    gl.deleteRenderbuffer(renderBuffer);
    gl.deleteFramebuffer(frameBuffer);

    //set back blending
    gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
    gl.enable(gl.BLEND);

    //decode ID (bit shifting by multiplication)
    var hasValue = result[3] != 0; //0 transparency is only for no-values
    if (hasValue) {
        var id = result[0] + result[1] * 256 + result[2] * 256 * 256;
        var handled = false;
        this._plugins.forEach(function (plugin) {
            if (!plugin.onBeforeGetId) {
                return;
            }
            handled = handled || plugin.onBeforeGetId(id);
        }, this);

        if (!handled)
            return id;
        else
            return null;
    }
    else {
        return null;
    }
