### ISSUE TITLE
Any possible to set multpile colors at same time for different space (Entity id)?

### ISSUE THREAD

**Issue by castronelson** [xBimTeam/XbimWebUI#272] opened 2020-01-23 08:01 UTC
Hi  I need to set different colors for at same time for spaces
But here the viewer taking last loaded RGBA color only.
kindly provide some solution

**Comment by martin1cerny** [comment] 2020-01-23 08:07
Duplicate of #271

**Closed by martin1cerny** 2020-01-23 08:07 UTC
