### ISSUE TITLE
Viewer doesn't work on mobile devices.

### ISSUE THREAD

**Issue by kolmar1991** [xBimTeam/XbimWebUI#367] opened 2021-09-05 15:15 UTC
Hi, I have noticed that the project in viewer on mobile devices (tablet, smartphone) with Android system is almost invisible. I have tried Chrome and Opera. I have also tried to turn on 'Desktop mode' and the issue still persist. Colours seem to be corrupted. It can be reproduced here https://docs.xbim.net/ (the example project at the bottom of the page). Is it a known issue? 

Best regards,
Marcin

**Comment by martin1cerny** [comment] 2021-09-06 07:39
"Almost invisible" is a bit hard to reproduce and investigate. Can you post a screenshot at least?

**Comment by kolmar1991** [comment] 2021-09-06 14:03
Sorry. I was sure, that it is reproducible on each android device.
Screen from other project:
<img width="340" alt="Screenshot 2021-09-06 at 15 58 02" src="https://user-images.githubusercontent.com/6024354/132228390-7ffd72e6-ddc7-4ab9-8d90-a13ca19ce4a8.png">
Screens from https://docs.xbim.net/examples/1_Hello_building.live.html
<img width="355" alt="Screenshot 2021-09-06 at 16 03 09" src="https://user-images.githubusercontent.com/6024354/132228993-9f743cca-28c8-4e26-8941-a6dfba2cc2a5.png">
<img width="363" alt="Screenshot 2021-09-06 at 16 03 42" src="https://user-images.githubusercontent.com/6024354/132229061-5620817d-5ed9-4684-b361-d15f5b06a7df.png">

**Comment by martin1cerny** [comment] 2021-09-06 14:06
Can you go to https://get.webgl.org/webgl2/ to see if your Android is using WebGL2?

**Comment by kolmar1991** [comment] 2021-09-06 14:10
It does.
![IMG_20210906_160957](https://user-images.githubusercontent.com/6024354/132229915-23deb2b8-4687-4f9b-947f-5a504fac3010.jpg)

**Comment by kolmar1991** [comment] 2021-09-19 16:15
Were you able to reproduce the issue? Is the root already known?

**Comment by martin1cerny** [comment] 2021-09-29 09:37
Hi @kolmar1991 , I can reproduce this on my phone. Will try to debug and fix in next few days. Sorry for a long response time, I'm deep in another project right now.

**Comment by cosay** [comment] 2021-10-18 17:37
It works well on Google Chrome on iPhone 11 but on Android:

https://docs.xbim.net/examples/1_Hello_building.live.html

Chrome version 94.0.4606.85 (same issue on Firefox and Opera on Android)
Android version: 11; RKQ1.200826.002 (and on other Android devices)

![obraz](https://user-images.githubusercontent.com/10207897/137778154-69e09c36-3b10-4a8f-be3f-f06e7865d9b6.png)

**Comment by martin1cerny** [comment] 2022-01-04 08:12
Hi @kolmar1991 and @cosay. I'm sorry for the long delay, but I finally got to this issue yesterday as the first development task in this year :-) 

The issue is caused by different implementation of the GLSL precision on Android. Our shader was declaring medium precision (better for performance) but for models in millimetres simple vector normalization in the shader was failing. 

I pushed the fix yesterday: [6bbd6dad1e580f50ef6871e8c155127ea5713fae](https://github.com/xBimTeam/XbimWebUI/commit/6bbd6dad1e580f50ef6871e8c155127ea5713fae)

Package: [2.0.1-pre202201031544](https://www.npmjs.com/package/@xbim/viewer/v/2.0.1-pre202201031544)

**Closed** 2022-01-04 08:16 UTC
