### ISSUE TITLE
Getting the world coordinate from a screen point on the model

### ISSUE THREAD

**Issue by fdeng1984** [xBimTeam/XbimWebUI#180] opened 2018-04-24 03:46 UTC
Hi,

When clicking a point  on the model, how to transform the screen coordinate to the world coordinate?
Is there any idea to implement it?

Thanks

**Comment by martin1cerny** [comment] 2018-04-24 06:25
Closing as a duplicate of https://github.com/xBimTeam/XbimWebUI/issues/77

**Closed by martin1cerny** 2018-04-24 06:25 UTC
